config/routes.rb
Rails.application.routes.draw do
  resources :artworks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    @artworks = Artwork.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: 'Artwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:title, :description, :height, :width, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/_form.html.erb
<%= form_with(model: artwork, local: true) do |form| %>
  <% if artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing Artwork</h1>

<%= render 'form', artwork: @artwork %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artworks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Height</th>
      <th>Width</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artworks.each do |artwork| %>
      <tr>
        <td><%= artwork.title %></td>
        <td><%= artwork.description %></td>
        <td><%= artwork.height %></td>
        <td><%= artwork.width %></td>
        <td><%= image_tag(artwork.image) %></td>
        <td><%= link_to 'Show', artwork %></td>
        <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
        <td><%= link_to 'Destroy', artwork, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @posts %>

<br>

<%= link_to 'New Artwork', new_artwork_path %>

app/views/artworks/new.html.erb
<h1>New Artwork</h1>

<%= render 'form', artwork: @artwork %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @artwork.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artwork.description %>
</p>

<p>
  <strong>Height:</strong>
  <%= @artwork.height %>
</p>

<p>
  <strong>Width:</strong>
  <%= @artwork.width %>
</p>

<p>
  <%= image_tag @artwork.image %>
</p>

<%= link_to 'Edit', edit_artwork_path(@artwork) %> |
<%= link_to 'Back', artworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>